image: Visual Studio 2017
version: 0.3.{build}-prerelease
configuration:
- Release
before_build:
- .paket\paket.exe restore
after_test:
- .paket\paket pack . --version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: iMA1b7JitywKpWnIRwd6E9C+2Dg/h/YWkKV31bNKuKsHQxXs3cMlgll81CNjzXyI
  on:
    branch: master
