image: Visual Studio 2017
version: 0.3.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-prerelease'
configuration:
- Release
before_build:
- .paket\paket.exe restore
after_test:
- .paket\paket pack . --version %APPVEYOR_BUILD_VERSION%-prerelease
artifacts:
- path: '*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: jrR5C53aeuTTfP90dmu+AeQOUss54msFxgCeLb9j0wBU+DK1hoY4E0XkKWP3p5NN
  on:
    branch: master
